### ISSUE TITLE
Faucet.py doesn't work well with Lagopus

### ISSUE THREAD

**Issue by Hong-Panha** [REANNZ/faucet#120]
I am doing the experiment with my mini-server running Lagopus as an open flow switch. I want to implement the Vlan into my network topology by using faucet.py throw ryu controller and it doesn't work. However, if i use OVS and create the network topology with mininet, the faucet.py work just fine. So my question is how can i get the faucet.py works with Lagopus ?

Thanks 
Panha

**Comment by KitL** [comment]
I've never used lagopus, could you show us the state of the flow table when
you use faucet as the controller?

**Comment by Hong-Panha** [comment]
Thanks for responding. I will send you later after i do the experiment again.

Panha

**Comment by Hong-Panha** [comment]
Hi,

I attach here some pictures for your reference.

Thanks,
Panha
![faucet_yaml](https://cloud.githubusercontent.com/assets/20162688/17014233/72a293c6-4f5e-11e6-8fe9-24010fcf1722.png)
![faucet_log](https://cloud.githubusercontent.com/assets/20162688/17014234/72dd065a-4f5e-11e6-8629-ed6ced487554.png)
![dp_py](https://cloud.githubusercontent.com/assets/20162688/17014235/72e015ca-4f5e-11e6-8902-f562d947db75.png)
![ryu_log](https://cloud.githubusercontent.com/assets/20162688/17014236/72e4aa9a-4f5e-11e6-8691-2b61d7fe87ca.png)

**Comment by anarkiwi** [comment]
There is no way to diagnose the problem on the information given (you did not send a flow table as requested). As you notice with OVS it works fine, so you probably installed your environment correctly.
Please troubleshoot your switch's flow table further, ensuring flows are present and will allow FAUCET to receive flows. If you can show that FAUCET does not send flows correctly please feel free to reopen with the details. At this stage it looks like a problem with your switch (configuration or implementation).

**Comment by Hong-Panha** [comment]
I am sorry but how to get that flow table ?

**Comment by anarkiwi** [comment]
I have not used Lagopus before so I'm sorry I don't know either. Perhaps a
Lagopus developer would be better able to help you.

**Comment by Hong-Panha** [comment]
Hi, 

I am sorry for not sending you the flow table on time. I just figured out how to get it. Below is the Flow table.

Lagosh> show flow
[
    {
        "tables": [
            {
                "table": 0, 
                "flows": [
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 9099, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "dl_dst": "01:80:c2:00:00:00"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 9099, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "dl_dst": "01:00:0c:cc:cc:cd"
                    }, 
                    {
                        "dl_type": 35020, 
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 9099, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "dl_src": "ff:ff:ff:ff:ff:ff", 
                        "actions": [], 
                        "priority": 9099, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "dl_src": "0e:00:00:00:00:01", 
                        "actions": [], 
                        "priority": 9001, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4196
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 1
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4196
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 2
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4196
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 3
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 4
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 5
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 6
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 7
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 8
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 9
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 10
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 11
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "push_vlan": 33024
                                    }, 
                                    {
                                        "vlan_vid": 4296
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 2
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "0", 
                        "in_port": 12
                    }, 
                    {
                        "stats": {
                            "packet_count": 39, 
                            "byte_count": 13819
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 0, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }
                ]
            }, 
            {
                "table": 1, 
                "flows": [
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 0, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }
                ]
            }, 
            {
                "table": 2, 
                "flows": [
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "controller"
                                    }
                                ]
                            }, 
                            {
                                "goto_table": 3
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 0, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }
                ]
            }, 
            {
                "table": 3, 
                "flows": [
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "goto_table": 4
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 0, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }
                ]
            }, 
            {
                "table": 4, 
                "flows": [
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 4
                                    }, 
                                    {
                                        "output": 5
                                    }, 
                                    {
                                        "output": 6
                                    }, 
                                    {
                                        "output": 7
                                    }, 
                                    {
                                        "output": 8
                                    }, 
                                    {
                                        "output": 9
                                    }, 
                                    {
                                        "output": 10
                                    }, 
                                    {
                                        "output": 11
                                    }, 
                                    {
                                        "output": 12
                                    }
                                ]
                            }
                        ], 
                        "priority": 9004, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4296", 
                        "dl_dst": "ff:ff:ff:ff:ff:ff"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 1
                                    }, 
                                    {
                                        "output": 2
                                    }, 
                                    {
                                        "output": 3
                                    }
                                ]
                            }
                        ], 
                        "priority": 9004, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4196", 
                        "dl_dst": "ff:ff:ff:ff:ff:ff"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 4
                                    }, 
                                    {
                                        "output": 5
                                    }, 
                                    {
                                        "output": 6
                                    }, 
                                    {
                                        "output": 7
                                    }, 
                                    {
                                        "output": 8
                                    }, 
                                    {
                                        "output": 9
                                    }, 
                                    {
                                        "output": 10
                                    }, 
                                    {
                                        "output": 11
                                    }, 
                                    {
                                        "output": 12
                                    }
                                ]
                            }
                        ], 
                        "priority": 9003, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4296", 
                        "dl_dst": "33:33:00:00:00:00/ff:ff:00:00:00:00"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 1
                                    }, 
                                    {
                                        "output": 2
                                    }, 
                                    {
                                        "output": 3
                                    }
                                ]
                            }
                        ], 
                        "priority": 9003, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4196", 
                        "dl_dst": "33:33:00:00:00:00/ff:ff:00:00:00:00"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 4
                                    }, 
                                    {
                                        "output": 5
                                    }, 
                                    {
                                        "output": 6
                                    }, 
                                    {
                                        "output": 7
                                    }, 
                                    {
                                        "output": 8
                                    }, 
                                    {
                                        "output": 9
                                    }, 
                                    {
                                        "output": 10
                                    }, 
                                    {
                                        "output": 11
                                    }, 
                                    {
                                        "output": 12
                                    }
                                ]
                            }
                        ], 
                        "priority": 9002, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4296", 
                        "dl_dst": "01:00:5e:00:00:00/ff:ff:ff:00:00:00"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 1
                                    }, 
                                    {
                                        "output": 2
                                    }, 
                                    {
                                        "output": 3
                                    }
                                ]
                            }
                        ], 
                        "priority": 9002, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4196", 
                        "dl_dst": "01:00:5e:00:00:00/ff:ff:ff:00:00:00"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 4
                                    }, 
                                    {
                                        "output": 5
                                    }, 
                                    {
                                        "output": 6
                                    }, 
                                    {
                                        "output": 7
                                    }, 
                                    {
                                        "output": 8
                                    }, 
                                    {
                                        "output": 9
                                    }, 
                                    {
                                        "output": 10
                                    }, 
                                    {
                                        "output": 11
                                    }, 
                                    {
                                        "output": 12
                                    }
                                ]
                            }
                        ], 
                        "priority": 9001, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4296", 
                        "dl_dst": "01:80:c2:00:00:00/01:80:c2:00:00:00"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 1
                                    }, 
                                    {
                                        "output": 2
                                    }, 
                                    {
                                        "output": 3
                                    }
                                ]
                            }
                        ], 
                        "priority": 9001, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4196", 
                        "dl_dst": "01:80:c2:00:00:00/01:80:c2:00:00:00"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 4
                                    }, 
                                    {
                                        "output": 5
                                    }, 
                                    {
                                        "output": 6
                                    }, 
                                    {
                                        "output": 7
                                    }, 
                                    {
                                        "output": 8
                                    }, 
                                    {
                                        "output": 9
                                    }, 
                                    {
                                        "output": 10
                                    }, 
                                    {
                                        "output": 11
                                    }, 
                                    {
                                        "output": 12
                                    }
                                ]
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4296"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "strip_vlan": null
                                    }, 
                                    {
                                        "output": 1
                                    }, 
                                    {
                                        "output": 2
                                    }, 
                                    {
                                        "output": 3
                                    }
                                ]
                            }
                        ], 
                        "priority": 9000, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928, 
                        "vlan_vid": "4196"
                    }, 
                    {
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "actions": [], 
                        "priority": 0, 
                        "idle_timeout": 0, 
                        "cookie": 1524372928
                    }
                ]
            }
        ], 
        "name": "bridge01", 
        "is-enabled": true
    }
]
