### ISSUE TITLE
tagged and untagged vlans as well as untagged ports accepting packets with vlan tags.

### ISSUE THREAD

**Issue by KitL** [REANNZ/faucet#16]
Currently if a port has tagged and untagged vlans,  the tagged vlan will overwrite the untagged rule.

This could be fixed by increasing the priority of the tagged vlan rules. But more importantly the switch really shouldnt accept tagged packets on ports with native vlans. We should require explicit configuration for QnQ when needed.

**Comment by anarkiwi** [comment]
OK. I just added a test to test separation of tagged/untagged VLANs. I'll
explicitly disallow tagged and untagged on the same port.

**Comment by anarkiwi** [comment]
OK, I did that. You now cannot have tagged and untagged on the same port -
doesn't even try.

**Comment by jimmyish** [comment]
I'm not sure I quite get this or if I'm misunderstanding what was done.

We wanted to keep the ability to receive tagged and untagged frames on a port. However, if I understood it, we didn't previously check if untagged frames were actually untagged, we simply assumed anything that wasn't a VLAN we expected was "untagged" and would get tagged into the native-vlan-id. This could effectively leads to us accidentally forming Q-in-Q frames for all unknown VLAN frames arriving.

I believe the aim was that any listed VLANs are passed untouched, untagged frames get tagged with native-vlan-id and any other frames are dropped.

Does that match with others views?

**Comment by anarkiwi** [comment]
Oh! I did not understand. Yes the code does not correctly drop
tagged-but-unconfigured VLANs. I'll fix that and then explicitly implement
tagged and untagged on the same port.

**Comment by vladimir-mencl-eresearch** [comment]
I'd just chip in: would allowing tagged and untagged on the same port 
would enable anyone on the untagged VLAN to spoof frames with any VLAN tags.

I'd see that as a risk - maybe it should be controlled by a config 
switch, like: --allow-me-to-shoot-myself-in-the-foot ?

Cheers,
Vlad

On 12/02/16 10:31, Josh Bailey wrote:
> Oh! I did not understand. Yes the code does not correctly drop
> tagged-but-unconfigured VLANs. I'll fix that and then explicitly implement
> tagged and untagged on the same port.
>
> On Thu, Feb 11, 2016 at 4:23 PM, Jamie Curtis <notifications@github.com>
> wrote:
>
>  > I'm not sure I quite get this or if I'm misunderstanding what was done.
>  >
>  > We wanted to keep the ability to receive tagged and untagged frames on a
>  > port. However, if I understood it, we didn't previously check if untagged
>  > frames were actually untagged, we simply assumed anything that wasn't a
>  > VLAN we expected was "untagged" and would get tagged into the
>  > native-vlan-id. This could effectively leads to us accidentally forming
>  > Q-in-Q frames for all unknown VLAN frames arriving.
>  >
>  > I believe the aim was that any listed VLANs are passed untouched,
> untagged
>  > frames get tagged with native-vlan-id and any other frames are dropped.
>  >
>  > Does that match with others views?
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/REANNZ/faucet/issues/16#issuecomment-183064547>.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/REANNZ/faucet/issues/16#issuecomment-183066551>.
>

-- 
Vladimir Mencl
Senior Software Engineer

Research & Education
Advanced Network NZ Ltd

P +64 3 364 3012
M +64 21 997352
E  vladimir.mencl@reannz.co.nz
www.reannz.co.nz

**Comment by jimmyish** [comment]
You can't be "on" the untagged VLAN and spoof a different VLAN tag, either the frame arrives with a tag or it does not. If the frame has no VLAN tag, you're in the untagged network, if the frame has a VLAN tag, either accept or drop it explicitly based on what is configured.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Jamie,

What is actually the use case for having untagged and tagged frames on a single port?

To rephrase my question, is there a risk by allowing this configuration?  If a (malicious) user is able to send frames that get forwarded without adding a tag, but the user spoofs the frames to start with a tag, then these would be interpreted as having arrived on that particular VLAN and might give the user access to a network the user should not have access to.

But to judge whether this risk is real, I'd need to understand what the use case for combiining untagged and tagged frames is - and where the untagged frames would originate from...

Cheers,
Vlad

**Comment by anarkiwi** [comment]
OK, I implemented this using the OF specific match for untagged packets:

duration=10s, n_packets=0, n_bytes=0, priority=9000,
*in_port=2,vlan_tci=0x0000/0x1fff*
,actions=push_vlan:0x8100,set_field:6136->vlan_vid,goto_table:2

If a port has both untagged and tagged VLANs configured, then the specific
matches are for untagged and those tagged VLANs. If you send a tagged VLAN
packet, with a tag that is not configured as a tagged VLAN, even if an
untagged VLAN is configured as well, that packet will be dropped.

The code is merged now.

Sorry for the delay, I was implementing IPs on VLANs on the controller
(adds some infrastructure necessary for static routes).
