### ISSUE TITLE
retire v1 config

### ISSUE THREAD

**Issue by anarkiwi** [REANNZ/faucet#232]
We should no longer support the "v1" standalone configuration type, as it can support only one dataplane, and we expect only "v2" and later on new installations. Tests currently support "v1" only and need to be migrated also.

**Comment by Callum027** [comment]
FaucetMultipleDPTest should come in handy for this. I tried to make it as configurable as possible in the hope that it could be used for all the tests, but it might need some work for the (relatively) irregularly configured ones.

**Comment by anarkiwi** [comment]
https://github.com/anarkiwi/faucet/commit/6769d16d18f03b39e3268c548d08d0e7412bb2ae

**Comment by anarkiwi** [comment]
All tests now use V2.

**Comment by gizmoguy** [comment]
@anarkiwi have we retired V1 config in current master ready for V1.3?

**Comment by anarkiwi** [comment]
I haven't yet, but totally willing to break it for v1.3.

**Comment by gizmoguy** [comment]
Yeah I think 1.3 is a good place to remove V1 support.

**Comment by anarkiwi** [comment]
Done.

https://github.com/REANNZ/faucet/commit/5d2ee50db7135d61aab79dcfe0a251e3fba3ad7f
