### ISSUE TITLE
should this ryu-faucet.conf file exist?

### ISSUE THREAD

**Issue by shivarammysore** [REANNZ/faucet#243]
faucet/src/ryu_faucet/org/onfsdn/faucet/ryu-faucet.conf

If so, what is the purpose?

**Comment by anarkiwi** [comment]
Thanks for the reminder.

It is required - I added comments to explain further. Basically, this
configures Ryu itself to more quickly detect a failed OF connection
(especially in the case where all learning has happened and the system is
relatively idle - by default there are no OF echoes sent and so it might be
quite some time before a OF connection failure is detected).

**Comment by shivarammysore** [comment]
So, should this conf file be in /etc/ryu/ directory?  How do you know that
Ryu is taking this conf file in?

Thanks

**Comment by anarkiwi** [comment]
You're right, it probably should; I just had it separate to avoid having to
merge it in to an installation that might have another Ryu controller
present (wouldn't want to stop on someone else's existing configuration).
We could perhaps change the installer to look for an existing ryu config,
if any and append these parameters if not present.

In my installation, I start ryu-manager with a CLI that points to this file
so I absolutely know it's being used.

**Comment by shivarammysore** [comment]
Fixed -

   - moved ryu-faucet.conf to src/cfg/etc/ryu/ryu.conf
   - Also updated the above ryu.conf to include things present in ryu.conf
   - Tested the same with pip package installation.
