### ISSUE TITLE
Faucet with Lagopus

### ISSUE THREAD

**Issue by Hong-Panha** [REANNZ/faucet#272]
Hi,

I am doing the experiment with my mini-server running Lagopus as an open flow switch. I want to implement the Vlan into my network topology by using faucet.py through ryu controller and it doesn't seem to work really well. However, if i use OVS and create the network topology with mininet, the faucet.py work just fine. So my question is how can i get the faucet.py works with Lagopus ?

![faucet](https://cloud.githubusercontent.com/assets/20162688/19755929/2590b17e-9c54-11e6-99f5-6e859eb00c24.png)

[Vlan flow.pdf](https://github.com/REANNZ/faucet/files/555030/Vlan.flow.pdf)

Thanks 
Panha

**Comment by anarkiwi** [comment]
Please refer to Lagopus developers as this appears to be specific to Lagopus. If you or they can identify an issue with FAUCET, please let us know and reopen with the details.
