### ISSUE TITLE
Parallel tests fail when run in docker.

### ISSUE THREAD

**Issue by KitL** [REANNZ/faucet#281]
I think there may be some serious issues around the thread safety of the parallel tests.

But on three separate environments the docker tests fail with a fresh pull from master. I have seen different sets of tests fail and if you run the tests singly or in serial they pass.

I think these issues may have existed for some time. I doubt it relates to any of the new code. But I haven't been able to find the cause.

**Comment by KitL** [comment]
Here is the log of Richard running the tests: https://paste.gizmoguy.net.nz/paste/mjrDsaf1#cxO8UOTfucKAPnEGCCZb-+iWYIVaevCNUghL/l5KsMF

And here is me:
https://paste.gizmoguy.net.nz/paste/pS7DzeJ+#7-BFbVfr+OhBQ5KVOYdddScGe4UUwX9qgBf5GZktPFC

Mine is a bit modified from me debugging the problem, but it is much the same each time..

**Comment by anarkiwi** [comment]
Definitely this needs investigation. Are the tests repeatedly failing in
the same way for the same tests, or are they flakey? Ie. Occasionally pass.

To narrow down the problem. What is the flakiest test?

**Comment by anarkiwi** [comment]
To follow this up; just reran with Trung's patches, and seems to be not
flakey on my dev environment. That is suggestive of races or other problems
that might arise in performance differences between environments.

If you can suggest tests that seem especially flakey for you both, I'd like
to see what I can put under stress on my system to determine why it is more
reliable.

**Comment by trungdtbk** [comment]
Here are the tests that fail almost every time I run
FaucetUntaggedControlPlaneTest
FaucetTaggedControlPlaneTest
FaucetStringOfDPACLOverrideTest

**Comment by anarkiwi** [comment]
Great. The control plane tests do involve the most interaction (because the
clients have to do ARP with the controller and then ping). It would make
sense that if there's a edgy timeout or dependency that it would be there.

I ran it again on mine and I don't see it. Therefore, we need to narrow
down why the clients can't ping the controller. I imagine that the problem
is they couldn't get a timely ARP response from the controller (if the
environment is loaded down by parallel tests). To experiment - it would be
good to add additional assertTrues that the clients can ARP for the
controller first. That will tell us if that's where the problem starts.

I have a feeling that when we configure a lot of parallel tests the
environment gets overloaded and the controller doesn't respond to the
client's ARP request in a timely manner. In which case configuring down the
max number of parallel tests would also help.

**Comment by trungdtbk** [comment]
I think this is the case. The system is overwhelmed and the controllers have no resource to answer ARP.
I added the assertTrue tests for checking ARP resolution and it fails.
It seems that the problem is partially fixed (ocasional failures) if we let the hosts more tries with ARP resolution.

**Comment by anarkiwi** [comment]
Great. Thanks for experimenting. I'm keen to hear what Chris and Richard's
experience is. Perhaps it's possible to add to the parallel test
dispatcher, to manage launching of new tests based on the system load
average. In the meantime we could also make the number of simultaneous
tests a bit more configurable so that people can tune that down for their
environment if required.

**Comment by KitL** [comment]
The FaucetStringOfDPACLOverrideTest would always fail in both environments.
If I commented out the first test method then the test would pass.
Printing out the flow table throughout the test showed that the flow table
was not modified after hupping.
Printing out the FAUCET_CONFIG environment indicated the correct file was
being used during the test.
Running the tests in Serial they would pass.
Running the tests individually they would pass.
Running small selections of tests (eg just the ones I had had problems
with) they would pass.

Hope this helps.

**Comment by anarkiwi** [comment]
OK. That gets us a bit further. For that particular test, if the flow table
isn't being updated, then that's the thing to debug next. Does the
faucet.log in the test directory show that the HUP was received and that
FAUCET tried to reconfigure? That of course should cause a bunch of
activity on the OF channel.

If FAUCET didn't get the HUP then perhaps something's going wrong in the
test method to do that. If it it is getting it then we we would want to
confirm with the ofchannel debug log that it actually sent flows.

**Comment by trungdtbk** [comment]
If the incremental reloading code is used then HUP will do nothing when unmeaningful changes are made (like adding /n).
I would change it so that when HUP with no change it reloads completely.

**Comment by anarkiwi** [comment]
I think though the user expectation is that if there are no changes then no
reload happens. That is certainly the convention with other systems (BIND,
DHCP etc).

It would definitely make more sense to actually change the config (Eg add a
new port or VLAN).

**Comment by KitL** [comment]
There definitely should be a way to force a reload even if config hasnt changed. And this probably shouldnt involve adding whitespace to a file. Faucet shouldnt ever be so confident that the switch is running what it thinks it is running that it should refuse to send its config to the switch.

I would suggest that if it sees a subtle change to config (eg a change of acls) then it tries not to be disruptive. But if it sees a significant change (eg a new port) or no changes at all (eg this is a request to refresh the config rather than modify it) then it should do the full refresh.

Back to the tests though. I tried to put together a temporary fix for docker today by adding a command line argument to the tests to force them to be run in serial. Unfortunately, it seems that running the tests in serial isnt actually guaranteeing that they will pass:

```
Ran 35 tests in 1150.172s

FAILED (failures=1)

======================================================================
FAIL: test_tagged (__main__.FaucetStackStringOfDPTaggedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 2060, in test_tagged
    self.assertEquals(0, self.net.pingAll())
AssertionError: 0 != 6.0606060606060606

None

real    19m33.789s
user    4m18.836s
sys     0m45.772s
```

So that is a bit of a problem.

So, in order to actually make some progress from here I am going to go ahead and build a second test suite. The idea being that we go down the path of having a separate set of unit and integration tests. New features will need to add tests for both. The unit tests will be easy to write and quick and easy to run. They shouldnt require the kind of extra privileges that the mininet tests need, and ideally they should just stick to standard libraries..

Then the mininet tests are just run when you are ready for your pull request. If you are running them in docker and you get random failures you can just retest the failed tests and verify they work when run individually.

I am going to add my serial command line option change anyway..

**Comment by vladimir-mencl-eresearch** [comment]
Hi @KitL 

Just trying to think about the user experience the reload will give...

As a hypothetical user, I would want to be able to force a full reload.  With the behaviour described above (no change == full reload), two reloads with no change to the config file in between would force a full reload.  It may feel slightly odd, but does the job...

Cheers,
Vlad

PS: Otherwise, I like the idea of separate unit and integration tests - I've seen it work well for other projects.

**Comment by anarkiwi** [comment]
I fully agree with both of Chris' points. I just observe though that you
can already force a full restart just be restarting the controller process.

In this way it behaves, now, already like BIND or DHCPD.

**Comment by anarkiwi** [comment]
Also. Yes point about assumptions what flows the switch has, but we still
have to ensure no one else is controlling the switch (except perhaps a
redundant FAUCET with the same config). That is also why we have default
drop configured in all tables. All the pieces have to be in place for
consistency and complexity management.

**Comment by anarkiwi** [comment]
Just another datapoint - I did a clean reinstall of Ubuntu 16, and upgraded
to OVS 2.6.1. I don't see any test failures.

**Comment by anarkiwi** [comment]
I just pushed a bunch of changes which include, among other things, a
socket server (the main process hands out ports dynamically to the clients,
to avoid the possibility that two parallel tests clients could both think
that they can use a dynamic port).

**Comment by anarkiwi** [comment]
And some other changes to rate limit the rate at which free ports are
handed out. This should increase reliability (it doesn't seem to delay
parallel testing much either).

Please let me know if the situation is improved?

**Comment by KitL** [comment]
Now I am getting this for every parallel test:
```
======================================================================
ERROR: __main__.FaucetUntaggedNoVLanUnicastFloodTest.test_untagged (subunit.RemotedTestCase)
__main__.FaucetUntaggedNoVLanUnicastFloodTest.test_untagged
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 350, in setUp
    self.start_net()
  File "./faucet_mininet_test.py", line 242, in start_net
    self.wait_for_tcp_listen(switch, switch.listenPort)
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 234, in wait_for_tcp_listen
    self.fail('%s never listened on port %u (%s)' % (host, port, fuser_out))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: s18f never listened on port 40422 (Cannot stat file /proc/60/fd/6: Stale file handle
Cannot stat file /proc/61/fd/6: Stale file handle
40422/tcp:              71
)
```

And for all the non parallel tests:
```======================================================================
ERROR: test_untagged (__main__.FaucetSingleUntaggedIPv6RouteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 350, in setUp
    self.start_net()
  File "./faucet_mininet_test.py", line 231, in start_net
    self.net = Mininet(self.topo, controller=FAUCET)
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 172, in __init__
    self.build()
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 442, in build
    self.buildFromTopo( self.topo )
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 429, in buildFromTopo
    self.addLink( **params )
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 364, in addLink
    link = cls( node1, node2, **options )
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 424, in __init__
    node1, node2, deleteIntfs=False )
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 468, in makeIntfPair
    deleteIntfs=deleteIntfs )
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 194, in makeIntfPair
    ( intf1, intf2, cmdOutput ) )
Exception: Error creating interface pair (u4b1-eth0,s14b-eth1): RTNETLINK answers: File exists```

**Comment by anarkiwi** [comment]
Looks like something in your environment is causing:

Cannot stat file /proc/61/fd/6: Stale file handle

I'll fix it to ignore it.

**Comment by anarkiwi** [comment]
OK, try that (was also just fixing hardware tests).

**Comment by KitL** [comment]
Looks like you fixed that up, but we still seem to have similar looking issues to what we had before

```======================================================================
FAIL: __main__.FaucetUntaggedControlPlaneTest.test_untagged (subunit.RemotedTestCase)
__main__.FaucetUntaggedControlPlaneTest.test_untagged
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 355, in test_untagged
    self.ping_all_when_learned()
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 312, in ping_all_when_learned
    self.assertEquals(0, self.net.pingAll())
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 16.666666666666668


======================================================================
FAIL: __main__.FaucetTaggedControlPlaneTest.test_tagged (subunit.RemotedTestCase)
__main__.FaucetTaggedControlPlaneTest.test_tagged
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 1234, in test_tagged
    self.ping_all_when_learned()
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 312, in ping_all_when_learned
    self.assertEquals(0, self.net.pingAll())
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 16.666666666666668
```

**Comment by anarkiwi** [comment]
Ahhh yes, looks like packet loss inside Mininet.

Well, that's sad. It looks like there's just not much to be done about it
other than run serialized by default.

**Comment by anarkiwi** [comment]
I added a retries for getting 0 loss (trying not to give up on parallel by
default). How is that for you?

**Comment by KitL** [comment]
Ok, current situation is that all the tests seem to run without great reliability, but much better than before.

However, The IPv6RouteTests are failing consistently.

```
======================================================================
FAIL: test_untagged (__main__.FaucetSingleUntaggedBGPIPv6RouteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 1500, in test_untagged
    self.wait_exabgp_sent_updates(self.exabgp_log)
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 510, in wait_exabgp_sent_updates
    self.fail('exabgp did not send BGP updates')
AssertionError: exabgp did not send BGP updates

======================================================================
FAIL: test_untagged (__main__.FaucetSingleUntaggedIPv6RouteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 1633, in test_untagged
    updates = self.exabgp_updates(self.exabgp_log)
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 499, in exabgp_updates
    self.fail('exabgp did not receive BGP updates')
AssertionError: exabgp did not receive BGP updates
```

**Comment by anarkiwi** [comment]
OK, that certainly is progress. Most of the changes I made were to prevent
possible TCP port collisions, which didn't happen on my machine much but
clearly were happening more elsewhere.

Those tests are very reliable here, so again it must be some kind of
environmental or other difference. If you can make it fail consistently,
then please remote the shutil.rmtree() call in tearDown() and send me the
logs from those test(s) directories - they contain all the exabgp and other
state and should allow me to figure out why exabgp thinks it didn't get BGP
updates.

**Comment by gizmoguy** [comment]
@KitL how are tests going for you now?

I was running them back to back yesterday when I was submitting my PRs and they seemed to work ok in docker.

Shall we close this issue off now?

**Comment by KitL** [comment]
Yep, josh seems to have gotten them pretty stable nowadays.
