### ISSUE TITLE
DPID imported from config is converted to decimal

### ISSUE THREAD

**Issue by abhayb-hpe** [REANNZ/faucet#296]
The function import_config reads the DPID from the hw_switch_config.yaml and stores it in decimal.
But the function get_config_header attempts to read it as a hex and converts it to decimal again and writes it into the faucet.yaml file.

**Comment by anarkiwi** [comment]
Fixed in https://github.com/anarkiwi/faucet/commit/4967c007cea17e1460d35e06e447c10067ebd977.
