### ISSUE TITLE
Faucet will crash when a datapath with no interfaces is listed in the configuration

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#324]
For robustness we probably shouldn't crash. Someone may try and reload Faucet into a new config with placeholder datapaths and find their instance crashes.

> Traceback (most recent call last):
>   File "/usr/local/bin/ryu-manager", line 11, in <module>
>     load_entry_point('ryu==4.8.1', 'console_scripts', 'ryu-manager')()
>   File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 91, in main
>     services.extend(app_mgr.instantiate_apps(**contexts))
>   File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
>     self._instantiate(app_name, cls, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 495, in _instantiate
>     app = cls(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/faucet.py", line 105, in __init__
>     self.config_file, self.logname)
>   File "/usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/config_parser.py", line 58, in dp_parser
>     config_hashes, dps = _dp_parser_v2(conf, config_file, logname)
>   File "/usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/config_parser.py", line 253, in _dp_parser_v2
>     for port_num, port_conf in ports_conf.iteritems():
> AttributeError: 'NoneType' object has no attribute 'iteritems'

**Comment by anarkiwi** [comment]
Verified that this no longer occurs and unittest added.

https://github.com/anarkiwi/faucet/commit/c35db6ae8cee3a9b64b5974c0c676cc0a3d976af
