### ISSUE TITLE
Python PIP package shouldn't install junk into /etc/ryu/faucet/

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#337]
At the moment when you pip install ryu-faucet you get a lot of files in the config directory /etc/ryu/faucet/:

> ubuntu@faucet:~/faucet$ ls /etc/ryu/faucet/
> faucet_demo_step1.yaml  faucet_demo_step2.yaml  faucet_demo_step3.yaml  faucet_Lagopus.yaml  faucet_ovs.yaml  faucet.yaml  faucet_ZodiacFX.yaml  gauge.yaml

And unfortunately faucet.yaml and gauge.yaml are installed as data files (which means when you pip uninstall ryu-faucet these files will be deleted as well even if they have user changes).

I propose we install a /etc/ryu/faucet/faucet.yaml-dist and /etc/ryu/faucet/gauge.yaml-dist which are fully featured configuration examples which users can copy into the appropriate file names and make their changes so that PIP doesn't step on your toes and delete them.

Another solution may also be to flag them as configuration files that PIP will assume that user changes will be made to these files and it won't delete them. I know you can do that with DEB files but I'm not familiar enough with PIP to know if the same concept exists?

**Comment by shivarammysore** [comment]
I have the /etc/ryu/faucet/*.yaml files as they also correspond to the
tutorial and demos that we have featured.  It is very useful for folks
getting started with Faucet.

Alternatively, we could build the *-dist.yaml file with all the comments
that one could use.

In regards to your question on flagging them as config files, I will check
on the same.

**Comment by gizmoguy** [comment]
I understand why the separate files exist, I don't fully understand why they need to all be installed.

Currently there is no way to delete those files (they will be reinstalled when you PIP install --upgrade ryu_faucet).

Some people like their configuration directories to be clean and tidy :)

**Comment by gizmoguy** [comment]
So how other projects handle this typically:

 * We could have an /etc/ryu/faucet/examples/ directory where these files are housed
 * We could install a /usr/share/doc/ryu/faucet/examples/ (or similar) directory where these files are housed

**Comment by shivarammysore** [comment]
I like the examples directory idea.  If you are going to git move the
files, I will sync the repo and update the pip packaging for the same
accordingly.

**Comment by shivarammysore** [comment]
Can we do a YAML scheme for faucet.yaml and this will enable us/users to
generate the yaml files lot more easily?  Maybe this can eliminate the
example files so that we can just change the schema and generate files.

**Comment by gizmoguy** [comment]
@shivarammysore check out PR#338 for review
