### ISSUE TITLE
Handle routing VLANs when dealing with multiple DPs better

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#348]
So at the moment doing BGP routing with multiple DPs is quite annoying. Officially faucet doesn't support this and you get the following error when you do:

> AssertionError: DPs ovs-nznog, at-x930-2 sharing a BGP speaker VLAN is unsupported

Now there is a workaround you can use to make faucet happy here, you can definite two vlans (e.g mynetwork_layer2 and mynetwork_layer3) with the same VLAN ID and push these out to different DPIDs so that routing happens in the right place.

Unfortunately I have discovered a limitation of this workaround to do with how faucet pushes VLANs to DPIDs. We assume all VLANs live on all DPIDs and populate the DP.vlans dictionary with all VLANs that are configured in faucet.yaml (this happens in config_parser.py in _dp_parser_v2()). What this means is that we have an ordering problem for the dps list in faucet.yaml. The DPID with the routing VLAN (mynetwork_layer3) must come first in faucet.yaml, if a DPID with the layer 2 version (mynetwork_layer2) we trip the assert on line 171 of config_parser.py.

Now the upshot of this is when you're using this multi-DP routing workaround is that you can't use the "include" keyword in faucet.yaml to include other config files as this implicitly reorders the dps list which can trigger the assert if you have a DPID with a name that sorts about your DPID with the routing VLAN.

Now I don't quite have enough time to think about the best way of solving any of these problems, but thought I'd write it down so we remember for later.

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/commit/13f08d7c583a46d3b14dda145ab09f72c05f9ab5
