### ISSUE TITLE
Gauge database error handling

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#353]
At the moment if we get a bad response from a database backend (i.e influxdb) gauge will crash with no error.

If we get the username/password wrong we will crash, if we get an error from influxdb on a query (such as bad datatype) we will crash.

We should add some error handling to the database connection and queries.

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/commit/2380dc31c21a738553f860140581054153c902c3 adds basic exception handling for InfluxDB.

Adding more tests also

**Comment by anarkiwi** [comment]
I have added the most basic possible tests (database down/up and that POST succeeds).
Could use more but at least the basics are there now.
