### ISSUE TITLE
Gauge with influxdb datatype issue

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#355]
So we have a bit of a dilemma with Gauge and InfluxDB support regarding datatypes.

OFP_PORT_STATS structs as defined by the OpenFlow spec contain uint64 values for each statistic.

InfluxDB uses int64 to store integers internally which leaves us with a large range of values that can't be stored currently, also due to issue #353 gauge will crash when it tries to store a value that doesn't fit in influx.

Maybe time to switch to float64?

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/commit/2380dc31c21a738553f860140581054153c902c3
