### ISSUE TITLE
Add config test feature to faucet

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#359]
So here's a great idea: if we can somehow run faucet in a mode where it just parses the config then exits returning either a success or error code depending on whether the config is valid or not then operators can use this as part of an ansible deploy to decide if it's safe to reload faucet or not.

Have assigned to Chris because he offered to code the feature for me in IRC :smile:

**Comment by anarkiwi** [comment]
I love that idea!

**Comment by anarkiwi** [comment]
https://github.com/anarkiwi/faucet/commit/489250cebd7f21e5d57dcd018810a4db0bffbf2e
