### ISSUE TITLE
Test fails to complete after git clone

### ISSUE THREAD

**Issue by Bairdo** [REANNZ/faucet#426]
```
faucet-1967 gauge-1967 
*** Starting 3 switches
s0b s0c s0d ...
*** Waiting for switches to connect
__main__.FaucetAPITest.test_api (subunit.RemotedTestCase)
__main__.FaucetAPITest.test_api ... FAIL
error: __main__.FaucetAPITest.test_api [
Traceback (most recent call last):
  File "/home/mininet/faucet/tests/faucet_mininet_test_base.py", line 212, in tearDown
    0, os.path.getsize(os.environ['FAUCET_EXCEPTION_LOG']))
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/tmp/faucet-tests-y6Typi/FaucetAPITest-test_api-JN9Gab/faucet-exception.log'
faucet-1967 gauge-1967 
*** Starting 3 switches
s0b s0c s0d ...
*** Waiting for switches to connect
__main__.FaucetAPITest.test_api (subunit.RemotedTestCase)
__main__.FaucetAPITest.test_api ... FAIL
error: __main__.FaucetAPITest.test_api [
Traceback (most recent call last):
  File "/home/mininet/faucet/tests/faucet_mininet_test_base.py", line 212, in tearDown
    0, os.path.getsize(os.environ['FAUCET_EXCEPTION_LOG']))
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/tmp/faucet-tests-y6Typi/FaucetAPITest-test_api-JN9Gab/faucet-exception.log'
]
*** Creating network
*** Adding controller
*** Adding hosts:
u131 u132 u141 u142 
*** Adding switches:
s13 s14 
*** Adding links:
(s13, s14) (u131, s13) (u132, s13) (u141, s14) (u142, s14) 
*** Configuring hosts
u131 u132 u141 u142 
*** Starting controller
faucet-1964 gauge-1964 
*** Starting 2 switches
s13 s14 ...
*** Waiting for switches to connect

```

On a fresh Ubuntu 16.04 server install, i get the above error when trying to run "sudo ./faucet_mininet_test.py". Where the test fails to progress for over 30 minutes.

I've installed all the dependencies that the test requests and cloned/installed [mininet](www.github.com/mininet/mininet)

commit d528da479d82a0efa9e73a4b5d8959f91c9f3cdf
mininet: 2.3.0d1
required binary/library ryu-manager --version version is 4.11
required binary/library ovs-vsctl --version version is 2.5
required binary/library tcpdump -h version is 4.9
required binary/library nc present (nc from the netcat-openbsd)
required binary/library vconfig present (the VLAN you are talking about)
required binary/library fuser -V version is 22.21
required binary/library mn --version version is 2.3
required binary/library exabgp --version version is 3.4
required binary/library pip show influxdb version is 4.0
required binary/library pylint --version version is 1.6
required binary/library curl --version version is 7.47
required binary/library ladvd -v version is 1.1

**Comment by Bairdo** [comment]
I then do
`pip install ryu-faucet` which makes the test complete. but with errors similar to

```======================================================================
ERROR: __main__.FaucetTaggedAndUntaggedTest.test_seperate_untagged_tagged (subunit.RemotedTestCase)
__main__.FaucetTaggedAndUntaggedTest.test_seperate_untagged_tagged
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 1130, in setUp
    self.start_net()
  File "./faucet_mininet_test.py", line 192, in start_net
    name='faucet', ports_sock=self.ports_sock, port=self.of_port))
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 173, in __init__
    self.build()
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 501, in build
    self.buildFromTopo( self.topo )
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 488, in buildFromTopo
    self.addLink( **params )
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 399, in addLink
    link = cls( node1, node2, **options )
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 450, in __init__
    node1, node2, deleteIntfs=False )
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 494, in makeIntfPair
    deleteIntfs=deleteIntfs )
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 195, in makeIntfPair
    ( intf1, intf2, cmdOutput ) )
Exception: Error creating interface pair (u131-eth0,s13-eth3): RTNETLINK answers: File exists


======================================================================
FAIL: __main__.FaucetTaggedIPv4RouteTest.test_tagged (subunit.RemotedTestCase)
__main__.FaucetTaggedIPv4RouteTest.test_tagged
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 1505, in test_tagged
    second_host, second_host_routed_ip)
  File "/home/mininet/faucet/tests/faucet_mininet_test_base.py", line 674, in verify_ipv4_routing
    with_group_table=with_group_table)
  File "/home/mininet/faucet/tests/faucet_mininet_test_base.py", line 627, in wait_for_route_as_flow
    'SET_FIELD: {eth_dst:%s}.+%s' % (nexthop, nw_dst_match), timeout)
  File "/home/mininet/faucet/tests/faucet_mininet_test_base.py", line 364, in wait_until_matching_flow
    msg=exp_flow)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: SET_FIELD: {eth_dst:e2:6f:7e:88:92:aa}.+"nw_dst": "10.0.2.0/255.255.255.0"
```

[facuet-test-error.txt](https://github.com/REANNZ/faucet/files/804973/facuet-test-error.txt)

**Comment by anarkiwi** [comment]
Looks like a couple of different problems. First problem - may be that
there is a missing dependency (which means the controller isn't starting).
Taking a look at the logs under /tmp/faucet-tests would be helpful.

When you pip install likely that corrects the missing dependencies. It
looks like something on the machine may be interfering with the tests. Is
this output from running the tests under docker? This is the preferred way
to avoid any potential interference from the host.

**Comment by shivarammysore** [comment]
when you do pip install, it pulls Faucet from pypi repository which is
1.3.2.  The test suite is using the code changes as of now.  So, you will
want to do from your git cloned repo is:

$ make
$ sudo -H pip install dist/ryu*gz

This will make sure you have the correct code.

Thanks

/Shivaram

**Comment by Bairdo** [comment]
Thanks Guys. The original tests were not from Docker. I've since tried running them with Docker but get a similar result.

I've had a look at the docker filesystem under 2 of the tests that fail and cannot see any obvious error messages.

[facuet-test-error-docker.txt](https://github.com/REANNZ/faucet/files/805517/facuet-test-error-docker.txt)

**Comment by anarkiwi** [comment]
I believe I found the problem - update_nexthop() would be a NOP, if the nexthop was expired but hadn't changed (it's a race, basically).

https://github.com/REANNZ/faucet/commit/58056630d7decaf5dc8f69cbe4fe60121c239a5e just now fixes it.

I need to add more extensive explicit tests of the various resolution paths to make sure they're all caught.

**Comment by Bairdo** [comment]
That seems to fix it. Thank you
