### ISSUE TITLE
Support python 3.x

### ISSUE THREAD

**Issue by anarkiwi** [REANNZ/faucet#466]

**Comment by gizmoguy** [comment]
Adding dependency on #473

**Comment by gizmoguy** [comment]
Adding dependency on #497

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/commit/969eeae58ff67a0b21f5e6700e2e6cf80445f937

FAUCET runs under python3 and passes all Docker tests.

Need to resolve a few remaining path import problems and we will be done.

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/releases/tag/v1_5_3
