### ISSUE TITLE
Gauge crash with watcher.stop()

### ISSUE THREAD

**Issue by dragonxtek** [REANNZ/faucet#470]
I'm running both faucet and gauge (last commit version 20c473c74062afbda06d6c58a20a0756631f7dc7). When I exit from mininet, with exit command, gauge crash, but faucet is still running. 
To reproduce the issue, you can run gauge and mininet as follows:
_ryu-manager --verbose  --ofp-tcp-listen-port=6663 ~/faucet/src/ryu_faucet/org/onfsdn/faucet/gauge.py_
_sudo mn --controller=remote,ip=127.0.0.1,port=6663 --topo linear,3_
After that, write exit command on mininet terminal.
My gauge.yaml config is the following:

faucet_configs:
    - '/etc/ryu/faucet/faucet.yaml'
watchers:
    port_status_poller:
        type: 'port_state'
        dps: ['s1','s2','s3','s4','s5','s6','s7','s8']
        interval: 10
        db: 'influx'

    port_stats_poller:
        type: 'port_stats'
        dps: ['s1','s2','s3','s4','s5','s6','s7','s8']
        interval: 10
        db: 'influx'

    port_table_poller:
        type: 'flow_table'
        dps: ['s1','s2','s3','s4','s5','s6','s7','s8']
        interval: 20
        #db: 'influx'
        db: 'ft_file'
dbs:

    ft_file:
        type: 'text'
        file: 'flow_table.JSON'
    influx:
        type: 'influx'
        influx_db: 'faucet'
        influx_host: '127.0.0.1'
        influx_port: 8086
        influx_user: ''
        influx_pwd: ''
        influx_timeout: 10

This is gauge.log:
Mar 15 17:32:22 gauge  INFO     DPID 1 (0x1) up
Mar 15 17:32:22 gauge  INFO     DPID 2 (0x2) up
Mar 15 17:32:22 gauge  INFO     DPID 3 (0x3) up
Mar 15 17:32:23 gauge.port_state INFO     port 1 deleted
Mar 15 17:32:23 gauge.port_state INFO     port 1 deleted
Mar 15 17:32:23 gauge.port_state INFO     port 1 deleted
Mar 15 17:32:23 gauge.port_state INFO     port 2 deleted
Mar 15 17:32:23 gauge.port_state INFO     port 2 deleted
Mar 15 17:32:24 gauge.port_state INFO     port 3 deleted
Mar 15 17:32:24 gauge.port_state INFO     port 2 deleted
Mar 15 17:32:24 gauge.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/home/nboettcher/Downloads/faucet/src/ryu_faucet/org/onfsdn/faucet/util.py", line 51, in __koe
    func(*args, **kwargs)
  File "/home/nboettcher/Downloads/faucet/src/ryu_faucet/org/onfsdn/faucet/gauge.py", line 99, in handler_connect_or_disconnect
    watcher.stop()
**TypeError: stop() takes exactly 2 arguments (1 given)**

Is a problem with watcher.stop(), but I don't know how to fix it.

**Comment by anarkiwi** [comment]
Sorry about that. There was a bug on shutdown. I just submitted a fix for
that. Thanks for reporting it.

**Comment by dragonxtek** [comment]
Thanks, now it's working
