### ISSUE TITLE
[BUG] dpid=0000000000000000 it's misinterpreted

### ISSUE THREAD

**Issue by dragonxtek** [REANNZ/faucet#477]
When I create a Switch in mininet with dpid=0000000000000000, ryu's app show me a random dpid like 51515168712262, when the last dpid is repeated.
```python
        for i in range(2):
            self.HostList.append(self.addHost('h' + str(i)))
            self.SwitchList.append(self.addSwitch('s' + str(i),dpid='000000000000000'+str(i)))
```
![selection_044](https://cloud.githubusercontent.com/assets/10552658/24167833/057ba68a-0e57-11e7-8a5e-a7e6205c6bd2.png)

You need to avoid this value, starting from 1:
```python
        for i in range(1,3):
            self.HostList.append(self.addHost('h' + str(i)))
            self.SwitchList.append(self.addSwitch('s' + str(i),dpid='000000000000000'+str(i)))
```
![selection_046](https://cloud.githubusercontent.com/assets/10552658/24168034/aec67a9e-0e57-11e7-9d80-20216c98cda9.png)

**Comment by gizmoguy** [comment]
Hi @dragonxtek 

Just looking to triage this, are you sure this is a bug for faucet and not for ryu?

I can't see where our code is causing you issues here.

**Comment by anarkiwi** [comment]
I don't see any reference to FAUCET here (this does appear to be a Ryu bug). Please re-open clarifying how this is a FAUCET bug and not a Ryu bug if you believe otherwise.
