### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by shivarammysore** [REANNZ/faucet#489]
I am using the git cloned version of faucet as of 3/29/2017.  Faucet logs shows:

```
Mar 29 16:46:18 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/faucet/valve_util.py", line 52, in __koe
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/faucet/faucet.py", line 420, in _packet_in_handler
    pkt = packet.Packet(msg.data)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/packet/packet.py", line 67, in __init__
    self._parser(parse_cls)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/packet/packet.py", line 76, in _parser
    proto, cls, rest_data = cls.parser(rest_data)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/packet/icmpv6.py", line 130, in parser
    msg.data = cls_.parser(buf, offset)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/packet/icmpv6.py", line 367, in parser
    options.append(option)
MemoryError
```
I don't have instructions to replicate it yet.  It is happening on my machine :-(  Will investigate more and add to this bug report.  But, I did want to make sure it is recorded.

**Comment by anarkiwi** [comment]
That looks like the Ryu packet parser crashed trying to parse a packet in.
A tcpdump (of the OF channel) will be required to figure it out. We could
also catch and discard the packet if the parser fails in a way we can catch.

**Comment by shivarammysore** [comment]
One more data point is that this controller was managing a switch with DPDK ports.

**Comment by anarkiwi** [comment]
That should not matter; the traceback shows a Ryu parser crash.

**Comment by gizmoguy** [comment]
Which version of ryu is in use here?

Also as per the Python documentation, basically the interpreter has run out of memory which may give you some clues:

> exception MemoryError
> 
>     Raised when an operation runs out of memory but the situation may still be rescued (by deleting some objects). The associated value is a string indicating what kind of (internal) operation ran out of memory. Note that because of the underlying memory management architecture (C’s malloc() function), the interpreter may not always be able to completely recover from this situation; it nevertheless raises an exception so that a stack traceback can be printed, in case a run-away program was the cause.

**Comment by shivarammysore** [comment]
Ryu Version: 4.11.  I just upgraded it to 4.12 and will keep an eye on this.

```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           7897         368        7084           1         445        7228
Swap:          8107          92        8015

# mpstat
Linux 4.8.0-22-generic (allbirds) 	03/29/2017 	_x86_64_	(2 CPU)

05:41:19 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
05:41:19 PM  all   23.13    0.01    0.55    2.13    0.00    0.03    0.00    0.00    0.00   74.15

```

**Comment by gizmoguy** [comment]
Hi @shivarammysore just checking in whether you saw this issue again?

If not I opt we close the ticket since we don't have a repro case.

**Comment by shivarammysore** [comment]
It is still occurring.   Attached is the TCP dump and the faucet.log file.  I think there is a memory leak ...

Also, `top` output:
```
top - 18:35:33 up 11:21,  2 users,  load average: 1.12, 1.20, 1.16
Tasks: 150 total,   2 running, 148 sleeping,   0 stopped,   0 zombie
%Cpu(s): 37.4 us,  0.6 sy,  0.0 ni, 59.9 id,  2.1 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8087516 total,   118792 free,  7895504 used,    73220 buff/cache
KiB Swap:  8302588 total,  5706432 free,  2596156 used.    18700 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5525 root      20   0 10.920g 7.297g   2316 R 100.0 94.6  24:04.02 ryu-manager
    1 root      20   0   55856   4440   3248 S   0.0  0.1   0:04.14 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.06 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
    7 root      20   0       0      0      0 S   0.0  0.0   0:02.99 rcu_sched
```


[memory_error.zip](https://github.com/REANNZ/faucet/files/904313/memory_error.zip)

**Comment by anarkiwi** [comment]
Looks like Ryu itself is getting upset by something.

The of channel dump doesn't seem to line up - it just has HELLOs over and
over with no other activity, and has timestamps for 1pm, but faucet.log has
timestamps for 6pm.

Is it possible please to get matching faucet.log and a pcap?

**Comment by shivarammysore** [comment]
Thanks for looking at this so quickly.  I will get it tomorrow.  I am running a overnight test and can't disturb the current setup now.

/Shivaram

**Comment by shivarammysore** [comment]
This bug seems to happen _inconsistently_ only when I manage a OVS switch with DPDK enabled interfaces (tested with OVS v2.7 with DPDK).  I will close the bug for now and reopen when I can get more detailed logs than the one I have provided so far.
