### ISSUE TITLE
Permanent learned port won't relearn after config reload.

### ISSUE THREAD

**Issue by Bairdo** [REANNZ/faucet#496]
When a change is made to the config file, and the reload is triggered by sending a SIGHUP, faucet removes rules from the eth_src_table.

However with the permanent_learn flag set, a MAC address that has been learnt on the permanent_learn port will not be re-learnt, and all it's packets will be dropped.

There is a rule for antispoofing here:
https://github.com/REANNZ/faucet/blob/master/faucet/valve_host.py#L121
that is installed for hosts on permanent_learn ports, which matches packets with the same MAC address, from any in_port and drops them. This means that as the MAC is no longer learned (rule was deleted on config reload) it is unable to be re-learnt.

From what I can tell, 
https://github.com/REANNZ/faucet/blob/master/faucet/valve.py#L702
and
https://github.com/REANNZ/faucet/blob/master/faucet/valve.py#L395-L401
is the code that deletes the rules from eth_src_table. and is matching on the in_port, which the antispoofing rule does not have.

Table 3 before:
```
cookie=0x5adc15c0, duration=195.089s, table=3, table=3, n_packets=148, n_bytes=14504, priority=9098,in_port=1,dl_vlan=100,dl_src=08:00:27:00:03:02 actions=goto_table:6
 cookie=0x5adc15c0, duration=195.050s, table=3, n_packets=147, n_bytes=14406, hard_timeout=300, priority=9098,in_port=2,dl_vlan=100,dl_src=52:54:00:12:35:02 actions=goto_table:6
 cookie=0x5adc15c0, duration=195.089s, table=3, n_packets=0, n_bytes=0, priority=9097,dl_vlan=100,dl_src=08:00:27:00:03:02 actions=drop
 cookie=0x5adc15c0, duration=196.030s, table=3, n_packets=0, n_bytes=0, priority=0 actions=drop
```
Table 3 after config reload:
```
 cookie=0x5adc15c0, duration=423.878s, table=3, n_packets=8, n_bytes=784, priority=9097,dl_vlan=100,dl_src=08:00:27:00:03:02 actions=drop
 cookie=0x5adc15c0, duration=424.819s, table=3, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x5adc15c0, duration=424.819s, table=3, n_packets=2, n_bytes=196, priority=9000 actions=CONTROLLER:128,goto_table:6
```

**Comment by gizmoguy** [comment]
Fixed by #519
