### ISSUE TITLE
FaucetStringOf*Test tests send Aruba pipeline definition to OVS/mininet

### ISSUE THREAD

**Issue by wackerly** [REANNZ/faucet#533]
I am attempting to run the FaucetStringOf*Test tests against a physical Aruba switch, but the test reports that an OFPErrorMsg was found in the debug log during tearDown().

```
ERROR: test_tagged (__main__.FaucetStackStringOfDPTaggedTest)
All tagged hosts in stack topology can reach each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/autotester/faucet/tests/faucet_mininet_test_base.py", line 223, in tearDown
    msg=('debug log has OFPErrorMsgs: %s' % debug_log))
AssertionError: debug log has OFPErrorMsgs

```
When I look at the debug log, the test is attempting to push a pipeline definition to another DPID and gets an error reported. I'm assuming that the test is attempting to stack a mininet switch with the physical Aruba switch. I think the catch here is that the mininet DPID doesn't support pipeline definition (see ArubaValve.switch_features() in valve.py). Perhaps the request is being sent because there's an Aruba switch involved in the setup?

I’ve attached the hw_switch_config.yaml file from my test setup, as well as the resulting ofchannel log where OFPErrorMsg was found (second line). Note that the DPID reported in the log is different from the DPID configured for the switch. I also don’t see this error message taken in a tcpdump of the ‘em2’ (control-plane) interface.
[issue.zip](https://github.com/REANNZ/faucet/files/972047/issue.zip)

**Comment by wackerly** [comment]
For what it's worth, at least a hack fix to this is to pass "Open vSwitch" rather than self.hardware to the call to self.get_config() in FaucetStringOfDPTest.build_net(..). In my case, the test case failed when using self.hardware ('Aruba') and passed when using "Open vSwitch".

**Comment by anarkiwi** [comment]
The multiswitch tests don't yet have a way to configure which switch in the test stack, you want the hardware switch to be. For the moment we now skip string tests when hardware based testing is enabled. There should be an additional way to configure different switches in a multi switch stack.

https://github.com/REANNZ/faucet/commit/986da8dd1b1e34595bf738afcfe5bff114a0c4cb for now - I added a TODO also to add that config infrastructure.
