### ISSUE TITLE
FAUCET resets gauge connection during unit test with hardware switch

### ISSUE THREAD

**Issue by wackerly** [REANNZ/faucet#565]
When I configure a FAUCET test harness to run against a physical switch (Aruba 3810), the test pauses indefinitely waiting for the gauge connection (self.net.waitConnected). This failure occurs only on 'master'. The test passes when run against 'v1_4_0'.

The attached console log shows the test output and hw_switch_config.yaml file. I also attached a packet capture of the control-plane during this test run, showing the Aruba switch (20.0.0.1) sending OFPT_ECHO_REQUEST, the test harness (20.0.0.2) sending OFPT_ECHO_REPLY, and then the test harness issuing a TCP reset.

[FaucetUntaggedTest.zip](https://github.com/REANNZ/faucet/files/984396/FaucetUntaggedTest.zip)

**Comment by anarkiwi** [comment]
Hi Shaun,

I think there is a problem in the environment here - works fine here on my
2930/.WC.16.03.0004 It would be good to use the all_tests.sh script, as it
verifies that things are cleaned up before starting the tests.

Also, if the test fails, it leaves behind a test directory under /tmp/ with
complete state. If the test still fails even under all_tests.sh please
attach contents of this directory.


root@faucet:~/faucet/tests# ./all_tests.sh FaucetUntaggedTest
ryu-manager: no process found
Cleaning up test interfaces, processes and openvswitch configuration from
previous test runs
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core
ovs-openflowd ovs-controller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core
ovs-openflowd ovs-controller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.
................
----------------------------------------------------------------------
Ran 16 tests in 0.558s

OK
{'packetin_pps': 0, 'drop_spoofed_faucet_mac': True,
'drop_broadcast_source_address': True, 'hardware': 'Open vSwitch',
'high_priority': 9001, 'table_offset': 0, 'arp_neighbor_timeout': 500,
'description': 'switch1', 'group_table': False, 'max_host_fib_retry_count':
10, 'eth_src_table': 3, 'priority_offset': 0, 'vlan_table': 1,
'highest_priority': 9099, 'dp_id': 3405705229, 'lowest_priority': 0,
'flood_table': 7, 'eth_dst_table': 6, 'port_acl_table': 0,
'vlan_acl_table': 2, 'ofchannel_log': None, 'ignore_learn_ins': 3,
'low_priority': 9000, 'interfaces': {}, 'ipv4_fib_table': 4,
'max_hosts_per_resolve_cycle': 5, 'cookie': 1524372928, 'stack': None,
'ipv6_fib_table': 5, 'max_resolve_backoff_time': 32, 'timeout': 300,
'drop_bpdu': True, 'drop_lldp': True}
.Error in file /tmp/tmp1qgm2t/faucet.yaml (while scanning for the next token
found character '\t' that cannot start any token
  in "/tmp/tmp1qgm2t/faucet.yaml", line 4, column 9)
.unknown top level config items: set(['unknown_thing'])
error found while loading config file: /tmp/tmp6hNxGi/faucet.yaml
Traceback (most recent call last):
  File "../faucet/check_faucet_config.py", line 33, in <module>
    if check_config(sys.argv[1:]):
  File "../faucet/check_faucet_config.py", line 19, in check_config
    parse_result = dp_parser(conf_file, logname)
  File "/home/faucet/faucet/faucet/config_parser.py", line 36, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
TypeError: 'NoneType' object is not iterable
.Error in config file: unknown config items in DP: set(['broken'])
Traceback (most recent call last):
  File "/home/faucet/faucet/faucet/config_parser.py", line 101, in
_dp_parser_v2
    dp = DP(identifier, dp_conf)
  File "/home/faucet/faucet/faucet/dp.py", line 131, in __init__
    assert not unknown_conf_names, 'unknown config items in DP: %s' %
unknown_conf_names
AssertionError: unknown config items in DP: set(['broken'])
Traceback (most recent call last):
  File "../faucet/check_faucet_config.py", line 33, in <module>
    if check_config(sys.argv[1:]):
  File "../faucet/check_faucet_config.py", line 24, in check_config
    for dp in dps:
TypeError: 'NoneType' object is not iterable
.
----------------------------------------------------------------------
Ran 4 tests in 2.872s

OK
........No handlers could be found for logger "test_valve.valve"
.................
----------------------------------------------------------------------
Ran 25 tests in 4.898s

OK
 * Exiting ovs-vswitchd (29983)
 * Exiting ovsdb-server (29969)
 * Starting ovsdb-server
 * system ID not configured, please use --system-id
 * Configuring Open vSwitch system IDs
 * Starting ovs-vswitchd
 * Enabling remote OVSDB managers
required binary/library ryu-manager --version version is 4.13
required binary/library ovs-vsctl --version version is 2.7
required binary/library tcpdump -h version is 4.9
required binary/library nc present (nc from the netcat-openbsd)
required binary/library vconfig present (the VLAN you are talking about)
required binary/library 2to3 --help present (Usage: 2to3)
required binary/library fuser -V version is 22.21
required binary/library mn --version version is 2.3
required binary/library exabgp --version version is 3.4
required binary/library pip show influxdb version is 4.0
required binary/library pylint --version version is 1.6
required binary/library curl --version version is 7.47
required binary/library ladvd -h version is 1.1
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
No config file found, using default configuration
Testing hardware, forcing test serialization
adding test FaucetUntaggedTest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running 0 tests in parallel and 1 tests serial
test_untagged (__main__.FaucetUntaggedTest)
All hosts on the same untagged VLAN should have connectivity. ... bridging
hardware switch DPID 453945588859328 (19cdc719241c0) dataplane via OVS DPID
453945588859329 (19cdc719241c1)
*** Creating network
*** Adding controller
*** Adding hosts:
u031 u032 u033 u034
*** Adding switches:
s03
*** Adding links:
(u031, s03) (u032, s03) (u033, s03) (u034, s03)
*** Configuring hosts
u031 u032 u033 u034
*** Starting controller
faucet-30713 gauge-30713
*** Starting 1 switches
s03 ...
*** Waiting for switches to connect
s03
u031 u031-eth0:s03-eth1
u032 u032-eth0:s03-eth2
u033 u033-eth0:s03-eth3
u034 u034-eth0:s03-eth4
*** Ping: testing ping reachability
u031 -> u032 u033 u034
u032 -> u031 u033 u034
u033 -> u031 u032 u034
u034 -> u031 u032 u033
*** Results: 0% dropped (12/12 received)
*** Stopping 2 controllers
faucet-30713 gauge-30713
*** Stopping 4 links
....
*** Stopping 1 switches
s03
*** Stopping 4 hosts
u031 u032 u033 u034
*** Done
ok

----------------------------------------------------------------------
Ran 1 test in 9.670s

OK

table: 0
  matches: ['in_port']
  table_instructions: ['OFPInstructionGotoTable']
  table_actions: []
table: 1
  matches: ['eth_dst', 'eth_src', 'eth_type', 'in_port', 'vlan_vid']
  table_instructions: ['OFPInstructionGotoTable']
  table_actions: ['OFPActionPushVlan', 'OFPActionSetField_vlan_vid']
table: 2
  matches: ['in_port']
  table_instructions: []
  table_actions: []
table: 3
  matches: ['eth_src', 'in_port', 'vlan_vid']
  table_instructions: ['OFPInstructionGotoTable']
  table_actions: ['OFPActionOutput']
table: 4
  matches: ['vlan_vid']
  table_instructions: []
  table_actions: []
table: 5
  matches: ['vlan_vid']
  table_instructions: []
  table_actions: []
table: 6
  matches: ['eth_dst', 'vlan_vid']
  table_instructions: ['OFPInstructionGotoTable']
  table_actions: ['OFPActionOutput', 'OFPActionPopVlan']
table: 7
  matches: ['eth_dst', 'eth_dst/ff:ff:00:00:00:00',
'eth_dst/ff:ff:ff:00:00:00', 'in_port', 'vlan_vid']
  table_instructions: []
  table_actions: ['OFPActionOutput', 'OFPActionPopVlan']

**Comment by wackerly** [comment]
The test case still fails using all_tests.sh, the output is attached. You'll notice that there's a failure to locate ovs-ctl partway through the output. Could that be an indicator of what's causing the problem when running the test? I wasn't aware that a dependency had been added for ovs-ctl between v1_4_0 and the latest master.

[FaucetUntaggedTest.zip](https://github.com/REANNZ/faucet/files/984998/FaucetUntaggedTest.zip)

**Comment by anarkiwi** [comment]
That's just a reference in all_tests.sh - we expect OVS to be installed
locally (as the Ubuntu install of OVS is too old).

Can you send the output of the failed test's directory under /tmp? That has
all the test state including automatically generated pcaps.

It still looks like something in the environment is not right.

**Comment by wackerly** [comment]
The /tmp/faucet-tests-x5pH_l/ is attached.
[FaucetUntaggedTest.tar.gz](https://github.com/REANNZ/faucet/files/985017/FaucetUntaggedTest.tar.gz)

**Comment by anarkiwi** [comment]
Thanks. I see that gauge is expected to start on 6644, but it's apparently
not starting at all - there's no gauge.log. Something must be stopping
gauge from running (eg conflicting process).

Check the logs in /tmp/gauge*.log - ryu should be able to tell you why it
isn't starting.


$ tcpdump -e -r gauge-13192-of.cap
reading from file gauge-13192-of.cap, link-type EN10MB (Ethernet)
08:49:05.077271 38:63:bb:c4:18:01 (oui Unknown) > d4:85:64:38:ac:e1 (oui
Unknown), ethertype IPv4 (0x0800), length 78: 20.0.0.1.65037 >
20.0.0.2.6644: Flags [S], seq 3086440115, win 65535, options [mss
1460,nop,wscale 1,nop,nop,sackOK,nop,nop,TS val 65039890 ecr 0], length 0
08:49:05.077322 d4:85:64:38:ac:e1 (oui Unknown) > 38:63:bb:c4:18:01 (oui
Unknown), ethertype IPv4 (0x0800), length 54: 20.0.0.2.6644 >
20.0.0.1.65037: Flags [R.], seq 0, ack 3086440116, win 0, length 0
08:49:14.529949 38:63:bb:c4:18:01 (oui Unknown) > d4:85:64:38:ac:e1 (oui
Unknown), ethertype IPv4 (0x0800), length 78: 20.0.0.1.60542 >
20.0.0.2.6644: Flags [S], seq 3088849519, win 65535, options [mss
1460,nop,wscale 1,nop,nop,sackOK,nop,nop,TS val 65049340 ecr 0], length 0
08:49:14.529992 d4:85:64:38:ac:e1 (oui Unknown) > 38:63:bb:c4:18:01 (oui
Unknown), ethertype IPv4 (0x0800), length 54: 20.0.0.2.6644 >
20.0.0.1.60542: Flags [R.], seq 0, ack 3088849520, win 0, length 0
08:49:24.528853 38:63:bb:c4:18:01 (oui Unknown) > d4:85:64:38:ac:e1 (oui
Unknown), ethertype IPv4 (0x0800), length 78: 20.0.0.1.60860 >
20.0.0.2.6644: Flags [S], seq 3091366397, win 65535, options [mss
1460,nop,wscale 1,nop,nop,sackOK,nop,nop,TS val 65059340 ecr 0], length 0
08:49:24.528900 d4:85:64:38:ac:e1 (oui Unknown) > 38:63:bb:c4:18:01 (oui
Unknown), ethertype IPv4 (0x0800), length 54: 20.0.0.2.6644 >
20.0.0.1.60860: Flags [R.], seq 0, ack 3091366398, win 0, length 0
08:49:34.529673 38:63:bb:c4:18:01 (oui Unknown) > d4:85:64:38:ac:e1 (oui
Unknown), ethertype IPv4 (0x0800), length 78: 20.0.0.1.59502 >
20.0.0.2.6644: Flags [S], seq 3093878346, win 65535, options [mss
1460,nop,wscale 1,nop,nop,sackOK,nop,nop,TS val 65069340 ecr 0], length 0
08:49:34.529720 d4:85:64:38:ac:e1 (oui Unknown) > 38:63:bb:c4:18:01 (oui
Unknown), ethertype IPv4 (0x0800), length 54: 20.0.0.2.6644 >
20.0.0.1.59502: Flags [R.], seq 0, ack 3093878347, win 0, length 0

**Comment by anarkiwi** [comment]
If you like, send me the entire contents of /tmp and I'd be happy to look.

**Comment by wackerly** [comment]
Got it! I found the following in the /tmp/gauge*.log file you pointed me to. After I ran "pip install numpy" the test completed as expected. As you suspected, this was a setup error.

loading app faucet.gauge
Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 78, in main
    app_mgr.load_apps(app_lists)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 415, in load_apps
    cls = self.load_app(app_cls_name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 392, in load_app
    mod = utils.import_module(name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/utils.py", line 116, in import_module
    mod = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/autotester/faucet/faucet/gauge.py", line 32, in <module>
    from watcher import watcher_factory
  File "/home/autotester/faucet/faucet/watcher.py", line 6, in <module>
    import numpy
ImportError: No module named numpy

**Comment by anarkiwi** [comment]
Great!

As a background note - re provide requirements.txt, so you can do "pip
install -r requirements.txt" to ensure things are in the correct state.
