### ISSUE TITLE
Test Failure FaucetTaggedIPv4RouteTest

### ISSUE THREAD

**Issue by Bairdo** [REANNZ/faucet#600]
FaucetTaggedIPv4RouteTest test will fail, when running on my development repository, using docker or travis to run the tests.

I have added a test class to the test suite and exported another variable to Prometheus. 

It does not occur if i comment out two other tests, for example 'FaucetLearn50MACsOnPortTest' and 'FaucetUntaggedHUPTest' or running 'FaucetTaggedIPv4RouteTest' on its own.

See https://travis-ci.org/Bairdo/faucet/builds/232648426#L6287 for full output.

With message:
```bash
======================================================================
FAIL: __main__.FaucetTaggedIPv4RouteTest.test_tagged (subunit.RemotedTestCase)
__main__.FaucetTaggedIPv4RouteTest.test_tagged
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "./faucet_mininet_test.py", line 2123, in test_tagged
    second_host, second_host_routed_ip)
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 896, in verify_ipv4_routing
    self.host_ipv4_alias(first_host, first_host_routed_ip)
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 847, in host_ipv4_alias
    self.assertEquals('', host.cmd(add_cmd))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '' != 'RTNETLINK answers: Numerical result out of range\r\n'
```

From what I can tell this is caused when the 'label' of the 'ip addr add' (see https://access.redhat.com/solutions/652593) is longer than 15 characters, in this case it is 16.
I have printed out the command to be: 'ip addr add 10.0.1.1/24 dev t11c1-eth0.100 label t11c1-eth0.100:1'
form
faucet_mininet_test_base.host_ipv4_alias():
...
     add_cmd = 'ip addr add %s dev %s label %s:1' % (
            alias_ip.with_prefixlen, host.intf(), host.intf())

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/commit/91b7104e108b1e7a16a8f9f243106952641e29f1

**Comment by anarkiwi** [comment]
Looks like still a problem, continuing to investigate.

**Comment by anarkiwi** [comment]
Looks like a new version of exabgp may have broken things:

Tue, 16 May 2017 04:56:16 | INFO     | 10014  | configuration | environment file missing
Tue, 16 May 2017 04:56:16 | INFO     | 10014  | configuration | generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env"
Tue, 16 May 2017 04:56:16 | INFO     | 10014  | reactor       | performing reload of exabgp 4.0.0-0478a014
Tue, 16 May 2017 04:56:16 | INFO     | 10014  | configuration | > group            | 'test'
Tue, 16 May 2017 04:56:16 | ERROR    | 10014  | configuration | problem with the configuration file, no change done
Tue, 16 May 2017 04:56:16 | ERROR    | 10014  | configuration | 
Tue, 16 May 2017 04:56:16 | ERROR    | 10014  | configuration | syntax error in section 
Tue, 16 May 2017 04:56:16 | ERROR    | 10014  | configuration | line 1: group test {
Tue, 16 May 2017 04:56:16 | ERROR    | 10014  | configuration | 
Tue, 16 May 2017 04:56:16 | ERROR    | 10014  | configuration | section group is invalid in root, 
root@faucet:/tmp/faucet-tests-wDr7WG/FaucetSingleUntaggedIPv4RouteTest-test_untagged-Knyv9m# more exabgp.conf 

group test {
  process test {
    encoder json;
    neighbor-changes;
    receive-routes;
    run /bin/cat;
  }
  router-id 2.2.2.2;
  neighbor 127.0.0.1 {
    passive;
    local-address 127.0.0.1;
    peer-as 1;
    local-as 2;
  }
}

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/commit/bcae6c576e761ef12c68ddc8e7c94f0aca73d7fc

**Comment by anarkiwi** [comment]
All passing again.

https://travis-ci.org/anarkiwi/faucet/builds/232688702
