### ISSUE TITLE
Faucet should support logrotate for rotating and compressing log files

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#731]
At the moment faucet rotates it's own log files with a TimedRotatingFileHandler():

https://github.com/REANNZ/faucet/blob/3de2edc668d00535cf5594aedce59d1156aa0090/faucet/valve_util.py#L81-L91

The downside is that we don't gzip these rotated logs so they quickly fill up the disk.

Instead of running gzip from inside faucet and waste CPU resources I vote we switch to using logrotate to rotate faucet.log and faucet_exception.log.

We can use a WatchedFileHandler() to check if when logrotate rotates the underlying file and we need to start writing to a new file descriptor:

https://docs.python.org/3/library/logging.handlers.html#watchedfilehandler

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/789
