### ISSUE TITLE
Attempting to apply multiple ACL rules to a port will crash faucet

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#754]
If we do say this:

>         interfaces:
>             1:
>                 name: "port1.0.1"
>                 native_vlan: redcables
>                 acl_in: [protect_from_access, capture_all]

We will get this:

> 
> Jul 13 16:07:51 faucet.exception ERROR    Unhandled exception, killing RYU
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 54, in __koe
>     func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/faucet/faucet.py", line 387, in _handler_datapath
>     dp_id, discovered_up_port_nums)
>   File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 625, in datapath_connect
>     ofmsgs.extend(self._add_ports_and_vlans(discovered_up_port_nums))
>   File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 580, in _add_ports_and_vlans
>     self.dp.dp_id, all_port_nums, cold_start=True))
>   File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 762, in ports_add
>     acl_ofmsgs = self._port_add_acl(port_num)
>   File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 646, in _port_add_acl
>     for rule_conf in self.dp.acls[acl_num].rules:
> TypeError: unhashable type: 'list'

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/757

Adds pretty basic default type checking to config classes which now catches this at parsing time.
