### ISSUE TITLE
ACL counters visibility in Gauge  

### ISSUE THREAD

**Issue by mbruyere** [REANNZ/faucet#761]
Could you please make the ACLs counters visible in gauge to be able to graphe them through
 influxDB Grafana or Prometheus.

Thx

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/787

Now supported in InfluxDB.

Add a Gauge watcher config, eg:

    flow_table:
        dps: ['faucet-1']
        type: 'flow_table'
        interval: 30
        db: 'influx'
