### ISSUE TITLE
FaucetUntaggedInfluxUnreachableTest needs a smaller timeout?

### ISSUE THREAD

**Issue by byllyfish** [REANNZ/faucet#793]
FaucetUntaggedInfluxUnreachableTest is failing on my system (latest master), but it looks like a problem with retries. By default, influxdb makes three attempts, but the test only waits 10 seconds for the "error shipping" string. Influx takes about 15 seconds to fail when the timeout is set to 5.

Setting the timeout in the config to 2 seconds fixes the issue.

```
        influx_timeout: 2
```

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/794
