### ISSUE TITLE
pylint error in gauge_influx.py

### ISSUE THREAD

**Issue by trungdtbk** [REANNZ/faucet#797]
I got this error when run faucet tests (on master)
Running pylint checks
************* Module faucet.gauge_influx
E:101, 8: Super of 'GaugePortStateInfluxDBLogger' has no 'update' member (no-member)
pylint of ../faucet/gauge_influx.py returns an error

**Comment by anarkiwi** [comment]
Looks like you got a bad push. Sorry about that. git pull and should be
fine.

When the repo moves outside of REANNZ we can automatically enforce this, at
the moment it's a manual check.
