### ISSUE TITLE
Minor things in latest commits

### ISSUE THREAD

**Issue by byllyfish** [REANNZ/faucet#873]
- In faucet.py, inside the handle_flowremoved function, the line ``valve = self.valves[ryu_dp.id]`` will raise an exception if ryu_dp.id is not registered in valves. (All the other handlers guard against this.)
- In valve.py, inside the flow_timeout method, the line ``in_port = eth_src = eth_dst = None`` should also set ``vid`` to None. The line ``eth_src = None`` at the top can be removed.

**Comment by anarkiwi** [comment]
Thanks - taken care of in today's monster test cleanup.
