### ISSUE TITLE
vlan.host_cache cleared after config reload.

### ISSUE THREAD

**Issue by Bairdo** [REANNZ/faucet#883]
I think there is an issue with the vlan.host_cache being cleared after a configuration reload and therefore the learned_macs prometheus export is also being cleared.

[FaucetConfigReloadTest.test_port_change_acl](https://github.com/REANNZ/faucet/compare/master...Bairdo:host-cache-test?expand=1#diff-19d413a10e47ab804405f7c8dd93d49bR1094) and in particular [FaucetConfigReloadTest._reload_conf](https://github.com/REANNZ/faucet/compare/master...Bairdo:host-cache-test?expand=1#diff-19d413a10e47ab804405f7c8dd93d49bR1061)  has been altered to show this.

Failing Travis-CI build https://travis-ci.org/Bairdo/faucet/builds/269029141

**Comment by anarkiwi** [comment]
Fixed in 1.6.0.
