### ISSUE TITLE
wait_for_flowremoved_msg bug?

### ISSUE THREAD

**Issue by byllyfish** [REANNZ/faucet#921]
Inside  ` wait_for_flowremoved_msg` in  faucet_mininet_test_unit.py, you have the following loop. I think you meant to indent the "if match" line so it is part of the inner for loop. Currently, the code will only succeed if the last ofchannel_log matches?

```python
        for i in range(timeout):
            for _, debug_log in self._get_ofchannel_logs():
                match = re.search(pattern, open(debug_log).read())
            if match:
                return
            time.sleep(1)

```

**Comment by anarkiwi** [comment]
Thanks for that, just taken care of after today's monster table refactor
(trying to incrementally OO-ify).

**Comment by byllyfish** [comment]
Thanks!  

Another thing I noticed: The ofchannel_log typically finds a FlowRemoved message with reason="DELETE" first. The test will pass, but may not test what you want. 

I included a log line filter for "IDLE_TIMEOUT". (OFPRR_IDLE_TIMEOUT=0).

**Comment by anarkiwi** [comment]
I don't intend to fix this at this time (use expire is unreliable for
several reasons and the unit test is marked skipped for this reason).
