### ISSUE TITLE
missing routes

### ISSUE THREAD

**Issue by trungdtbk** [REANNZ/faucet#93]
routes are missed with the add_resolved_routes method.
if multiple routes share the same gateway, only the first one is added to eth_src_table.

**Comment by gizmoguy** [comment]
Hey @trungdtbk thanks for your bug report!

I'm just triaging this bug now and wondering if PR #94 submitted by you fixes this issue or if this is another separate issue?

**Comment by trungdtbk** [comment]
Yes, it is for the routing issue. I just added the uni test in PR #94.

**Comment by KitL** [comment]
Cool, thanks!
